apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservice-overview
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: postgres
  DB_NAME: microservice_overview
  DEV_MODE: "false"

