apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: microservice-overview
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: microservice_overview

